name: Excavator
on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '10 */4 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Set Git Name And Email
      run: |
        $user = if ($env:USER_NAME) { $env:USER_NAME } else { 'github-actions[bot]' }
        $email = if ($env:USER_EMAIL) { $env:USER_EMAIL } else { 'github-actions[bot]@users.noreply.github.com' }
        # $rem = "https://${env:GITHUB_ACTOR}:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPOSITORY.git"
        git config --global user.name $user
        git config --global user.email $email
    - name: Update Zig
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $content = (Invoke-WebRequest -Uri https://ziglang.org/download/index.json -UseBasicParsing).Content
        $url = $content | ConvertFrom-Json | Select-Object -ExpandProperty master | Select-Object -ExpandProperty x86_64-linux | Select-Object -ExpandProperty tarball
        # $sha256 = $content | ConvertFrom-Json | Select-Object -ExpandProperty master | Select-Object -ExpandProperty x86_64-linux | Select-Object -ExpandProperty shasum
        $url -match 'zig-linux-x86_64-(.+)\.tar\.xz'
        $version = $Matches[1]
        (new-object System.Net.WebClient).DownloadFile($url,'zig-linux-x86_64.tar.xz')
        $sha256 = (Get-FileHash -Algorithm SHA256 'zig-linux-x86_64.tar.xz').Hash
        rm zig-linux-x86_64.tar.xz

        # 打印url和sha256
        Write-Output $url
        Write-Output $sha256
        Write-Output $version
        # 打开zig_latest.rb文件
        $zig_latest_rb = Get-Content -Path zig_latest.rb
        # 替换url和sha256
        $zig_latest_rb = $zig_latest_rb -replace 'url .+', "url `"$url`""
        $zig_latest_rb = $zig_latest_rb -replace 'sha256 .+', "sha256 `"$sha256`""
        $zig_latest_rb = $zig_latest_rb -replace 'version .+', "version `"$version`""
        # 写入zig_latest.rb文件
        $zig_latest_rb | Set-Content -Path zig_latest.rb

        # Hub Push
        hub commit -a -m "zig_latest: Update to version $version"
        hub push
